export interface Card {
  id?: string
  absoluteNum: number
  teamNum: number
  playerName: null
  isSelected: boolean
  team: string
}[]


export const cardsDb: Card[] = [
  {
    absoluteNum: 1,
    teamNum: 1,
    playerName: null,
    isSelected: false,
    team: "CL",
  },
  {
    absoluteNum: 2,
    teamNum: 2,
    playerName: null,
    isSelected: false,
    team: "CL",
  },
  {
    absoluteNum: 3,
    teamNum: 3,
    playerName: null,
    isSelected: false,
    team: "CL",
  },
  {
    absoluteNum: 4,
    teamNum: 4,
    playerName: null,
    isSelected: false,
    team: "CL",
  },
  {
    absoluteNum: 5,
    teamNum: 5,
    playerName: null,
    isSelected: false,
    team: "CL",
  },
  {
    absoluteNum: 6,
    teamNum: 6,
    playerName: null,
    isSelected: false,
    team: "CL",
  },
  {
    absoluteNum: 7,
    teamNum: 7,
    playerName: null,
    isSelected: false,
    team: "CL",
  },
  {
    absoluteNum: 8,
    teamNum: 8,
    playerName: null,
    isSelected: false,
    team: "CL",
  },
  {
    absoluteNum: 9,
    teamNum: 9,
    playerName: null,
    isSelected: false,
    team: "CL",
  },
  {
    absoluteNum: 10,
    teamNum: 1,
    playerName: null,
    isSelected: false,
    team: "Aucas",
  },
  {
    absoluteNum: 11,
    teamNum: 2,
    playerName: null,
    isSelected: false,
    team: "Aucas",
  },
  {
    absoluteNum: 12,
    teamNum: 3,
    playerName: null,
    isSelected: false,
    team: "Aucas",
  },
  {
    absoluteNum: 13,
    teamNum: 4,
    playerName: null,
    isSelected: false,
    team: "Aucas",
  },
  {
    absoluteNum: 14,
    teamNum: 5,
    playerName: null,
    isSelected: false,
    team: "Aucas",
  },
  {
    absoluteNum: 15,
    teamNum: 6,
    playerName: null,
    isSelected: false,
    team: "Aucas",
  },
  {
    absoluteNum: 16,
    teamNum: 7,
    playerName: null,
    isSelected: false,
    team: "Aucas",
  },
  {
    absoluteNum: 17,
    teamNum: 8,
    playerName: null,
    isSelected: false,
    team: "Aucas",
  },
  {
    absoluteNum: 18,
    teamNum: 9,
    playerName: null,
    isSelected: false,
    team: "Aucas",
  },
  {
    absoluteNum: 19,
    teamNum: 10,
    playerName: null,
    isSelected: false,
    team: "Aucas",
  },
  {
    absoluteNum: 20,
    teamNum: 11,
    playerName: null,
    isSelected: false,
    team: "Aucas",
  },
  {
    absoluteNum: 21,
    teamNum: 12,
    playerName: null,
    isSelected: false,
    team: "Aucas",
  },
  {
    absoluteNum: 22,
    teamNum: 13,
    playerName: null,
    isSelected: false,
    team: "Aucas",
  },
  {
    absoluteNum: 23,
    teamNum: 14,
    playerName: null,
    isSelected: false,
    team: "Aucas",
  },
  {
    absoluteNum: 24,
    teamNum: 15,
    playerName: null,
    isSelected: false,
    team: "Aucas",
  },
  {
    absoluteNum: 25,
    teamNum: 16,
    playerName: null,
    isSelected: false,
    team: "Aucas",
  },
  {
    absoluteNum: 26,
    teamNum: 17,
    playerName: null,
    isSelected: false,
    team: "Aucas",
  },
  {
    absoluteNum: 27,
    teamNum: 18,
    playerName: null,
    isSelected: false,
    team: "Flamengo",
  },
  {
    absoluteNum: 28,
    teamNum: 19,
    playerName: null,
    isSelected: false,
    team: "Flamengo",
  },
  {
    absoluteNum: 29,
    teamNum: 20,
    playerName: null,
    isSelected: false,
    team: "Flamengo",
  },
  {
    absoluteNum: 30,
    teamNum: 21,
    playerName: null,
    isSelected: false,
    team: "Flamengo",
  },
  {
    absoluteNum: 31,
    teamNum: 22,
    playerName: null,
    isSelected: false,
    team: "Flamengo",
  },
  {
    absoluteNum: 32,
    teamNum: 23,
    playerName: null,
    isSelected: false,
    team: "Flamengo",
  },
  {
    absoluteNum: 33,
    teamNum: 24,
    playerName: null,
    isSelected: false,
    team: "Flamengo",
  },
  {
    absoluteNum: 34,
    teamNum: 25,
    playerName: null,
    isSelected: false,
    team: "Flamengo",
  },
  {
    absoluteNum: 35,
    teamNum: 26,
    playerName: null,
    isSelected: false,
    team: "Flamengo",
  },
  {
    absoluteNum: 36,
    teamNum: 27,
    playerName: null,
    isSelected: false,
    team: "Flamengo",
  },
  {
    absoluteNum: 37,
    teamNum: 28,
    playerName: null,
    isSelected: false,
    team: "Flamengo",
  },
  {
    absoluteNum: 38,
    teamNum: 29,
    playerName: null,
    isSelected: false,
    team: "Flamengo",
  },
  {
    absoluteNum: 39,
    teamNum: 30,
    playerName: null,
    isSelected: false,
    team: "Flamengo",
  },
  {
    absoluteNum: 40,
    teamNum: 31,
    playerName: null,
    isSelected: false,
    team: "Flamengo",
  },
  {
    absoluteNum: 41,
    teamNum: 32,
    playerName: null,
    isSelected: false,
    team: "Flamengo",
  },
  {
    absoluteNum: 42,
    teamNum: 33,
    playerName: null,
    isSelected: false,
    team: "Flamengo",
  },
  {
    absoluteNum: 43,
    teamNum: 34,
    playerName: null,
    isSelected: false,
    team: "Flamengo",
  },
  {
    absoluteNum: 44,
    teamNum: 35,
    playerName: null,
    isSelected: false,
    team: "Ñublense",
  },
  {
    absoluteNum: 45,
    teamNum: 36,
    playerName: null,
    isSelected: false,
    team: "Ñublense",
  },
  {
    absoluteNum: 46,
    teamNum: 37,
    playerName: null,
    isSelected: false,
    team: "Ñublense",
  },
  {
    absoluteNum: 47,
    teamNum: 38,
    playerName: null,
    isSelected: false,
    team: "Ñublense",
  },
  {
    absoluteNum: 48,
    teamNum: 39,
    playerName: null,
    isSelected: false,
    team: "Ñublense",
  },
  {
    absoluteNum: 49,
    teamNum: 40,
    playerName: null,
    isSelected: false,
    team: "Ñublense",
  },
  {
    absoluteNum: 50,
    teamNum: 41,
    playerName: null,
    isSelected: false,
    team: "Ñublense",
  },
  {
    absoluteNum: 51,
    teamNum: 42,
    playerName: null,
    isSelected: false,
    team: "Ñublense",
  },
  {
    absoluteNum: 52,
    teamNum: 43,
    playerName: null,
    isSelected: false,
    team: "Ñublense",
  },
  {
    absoluteNum: 53,
    teamNum: 44,
    playerName: null,
    isSelected: false,
    team: "Ñublense",
  },
  {
    absoluteNum: 54,
    teamNum: 45,
    playerName: null,
    isSelected: false,
    team: "Ñublense",
  },
  {
    absoluteNum: 55,
    teamNum: 46,
    playerName: null,
    isSelected: false,
    team: "Ñublense",
  },
  {
    absoluteNum: 56,
    teamNum: 47,
    playerName: null,
    isSelected: false,
    team: "Ñublense",
  },
  {
    absoluteNum: 57,
    teamNum: 48,
    playerName: null,
    isSelected: false,
    team: "Ñublense",
  },
  {
    absoluteNum: 58,
    teamNum: 49,
    playerName: null,
    isSelected: false,
    team: "Ñublense",
  },
  {
    absoluteNum: 59,
    teamNum: 50,
    playerName: null,
    isSelected: false,
    team: "Ñublense",
  },
  {
    absoluteNum: 60,
    teamNum: 51,
    playerName: null,
    isSelected: false,
    team: "Ñublense",
  },
  {
    absoluteNum: 61,
    teamNum: 52,
    playerName: null,
    isSelected: false,
    team: "Racing",
  },
  {
    absoluteNum: 62,
    teamNum: 53,
    playerName: null,
    isSelected: false,
    team: "Racing",
  },
  {
    absoluteNum: 63,
    teamNum: 54,
    playerName: null,
    isSelected: false,
    team: "Racing",
  },
  {
    absoluteNum: 64,
    teamNum: 55,
    playerName: null,
    isSelected: false,
    team: "Racing",
  },
  {
    absoluteNum: 65,
    teamNum: 56,
    playerName: null,
    isSelected: false,
    team: "Racing",
  },
  {
    absoluteNum: 66,
    teamNum: 57,
    playerName: null,
    isSelected: false,
    team: "Racing",
  },
  {
    absoluteNum: 67,
    teamNum: 58,
    playerName: null,
    isSelected: false,
    team: "Racing",
  },
  {
    absoluteNum: 68,
    teamNum: 59,
    playerName: null,
    isSelected: false,
    team: "Racing",
  },
  {
    absoluteNum: 69,
    teamNum: 60,
    playerName: null,
    isSelected: false,
    team: "Racing",
  },
  {
    absoluteNum: 70,
    teamNum: 61,
    playerName: null,
    isSelected: false,
    team: "Racing",
  },
  {
    absoluteNum: 71,
    teamNum: 62,
    playerName: null,
    isSelected: false,
    team: "Racing",
  },
  {
    absoluteNum: 72,
    teamNum: 63,
    playerName: null,
    isSelected: false,
    team: "Racing",
  },
  {
    absoluteNum: 73,
    teamNum: 64,
    playerName: null,
    isSelected: false,
    team: "Racing",
  },
  {
    absoluteNum: 74,
    teamNum: 65,
    playerName: null,
    isSelected: false,
    team: "Racing",
  },
  {
    absoluteNum: 75,
    teamNum: 66,
    playerName: null,
    isSelected: false,
    team: "Racing",
  },
  {
    absoluteNum: 76,
    teamNum: 67,
    playerName: null,
    isSelected: false,
    team: "Racing",
  },
  {
    absoluteNum: 77,
    teamNum: 68,
    playerName: null,
    isSelected: false,
    team: "Racing",
  },
  {
    absoluteNum: 78,
    teamNum: 69,
    playerName: null,
    isSelected: false,
    team: "Independiente Medellín",
  },
  {
    absoluteNum: 79,
    teamNum: 70,
    playerName: null,
    isSelected: false,
    team: "Independiente Medellín",
  },
  {
    absoluteNum: 80,
    teamNum: 71,
    playerName: null,
    isSelected: false,
    team: "Independiente Medellín",
  },
  {
    absoluteNum: 81,
    teamNum: 72,
    playerName: null,
    isSelected: false,
    team: "Independiente Medellín",
  },
  {
    absoluteNum: 82,
    teamNum: 73,
    playerName: null,
    isSelected: false,
    team: "Independiente Medellín",
  },
  {
    absoluteNum: 83,
    teamNum: 74,
    playerName: null,
    isSelected: false,
    team: "Independiente Medellín",
  },
  {
    absoluteNum: 84,
    teamNum: 75,
    playerName: null,
    isSelected: false,
    team: "Independiente Medellín",
  },
  {
    absoluteNum: 85,
    teamNum: 76,
    playerName: null,
    isSelected: false,
    team: "Independiente Medellín",
  },
  {
    absoluteNum: 86,
    teamNum: 77,
    playerName: null,
    isSelected: false,
    team: "Independiente Medellín",
  },
  {
    absoluteNum: 87,
    teamNum: 78,
    playerName: null,
    isSelected: false,
    team: "Independiente Medellín",
  },
  {
    absoluteNum: 88,
    teamNum: 79,
    playerName: null,
    isSelected: false,
    team: "Independiente Medellín",
  },
  {
    absoluteNum: 89,
    teamNum: 80,
    playerName: null,
    isSelected: false,
    team: "Independiente Medellín",
  },
  {
    absoluteNum: 90,
    teamNum: 81,
    playerName: null,
    isSelected: false,
    team: "Independiente Medellín",
  },
  {
    absoluteNum: 91,
    teamNum: 82,
    playerName: null,
    isSelected: false,
    team: "Independiente Medellín",
  },
  {
    absoluteNum: 92,
    teamNum: 83,
    playerName: null,
    isSelected: false,
    team: "Independiente Medellín",
  },
  {
    absoluteNum: 93,
    teamNum: 84,
    playerName: null,
    isSelected: false,
    team: "Independiente Medellín",
  },
  {
    absoluteNum: 94,
    teamNum: 85,
    playerName: null,
    isSelected: false,
    team: "Independiente Medellín",
  },
  {
    absoluteNum: 95,
    teamNum: 86,
    playerName: null,
    isSelected: false,
    team: "Internacional",
  },
  {
    absoluteNum: 96,
    teamNum: 87,
    playerName: null,
    isSelected: false,
    team: "Internacional",
  },
  {
    absoluteNum: 97,
    teamNum: 88,
    playerName: null,
    isSelected: false,
    team: "Internacional",
  },
  {
    absoluteNum: 98,
    teamNum: 89,
    playerName: null,
    isSelected: false,
    team: "Internacional",
  },
  {
    absoluteNum: 99,
    teamNum: 90,
    playerName: null,
    isSelected: false,
    team: "Internacional",
  },
  {
    absoluteNum: 100,
    teamNum: 91,
    playerName: null,
    isSelected: false,
    team: "Internacional",
  },
  {
    absoluteNum: 101,
    teamNum: 92,
    playerName: null,
    isSelected: false,
    team: "Internacional",
  },
  {
    absoluteNum: 102,
    teamNum: 93,
    playerName: null,
    isSelected: false,
    team: "Internacional",
  },
  {
    absoluteNum: 103,
    teamNum: 94,
    playerName: null,
    isSelected: false,
    team: "Internacional",
  },
  {
    absoluteNum: 104,
    teamNum: 95,
    playerName: null,
    isSelected: false,
    team: "Internacional",
  },
  {
    absoluteNum: 105,
    teamNum: 96,
    playerName: null,
    isSelected: false,
    team: "Internacional",
  },
  {
    absoluteNum: 106,
    teamNum: 97,
    playerName: null,
    isSelected: false,
    team: "Internacional",
  },
  {
    absoluteNum: 107,
    teamNum: 98,
    playerName: null,
    isSelected: false,
    team: "Internacional",
  },
  {
    absoluteNum: 108,
    teamNum: 99,
    playerName: null,
    isSelected: false,
    team: "Internacional",
  },
  {
    absoluteNum: 109,
    teamNum: 100,
    playerName: null,
    isSelected: false,
    team: "Internacional",
  },
  {
    absoluteNum: 110,
    teamNum: 101,
    playerName: null,
    isSelected: false,
    team: "Internacional",
  },
  {
    absoluteNum: 111,
    teamNum: 102,
    playerName: null,
    isSelected: false,
    team: "Internacional",
  },
  {
    absoluteNum: 112,
    teamNum: 103,
    playerName: null,
    isSelected: false,
    team: "Metropolitanos",
  },
  {
    absoluteNum: 113,
    teamNum: 104,
    playerName: null,
    isSelected: false,
    team: "Metropolitanos",
  },
  {
    absoluteNum: 114,
    teamNum: 105,
    playerName: null,
    isSelected: false,
    team: "Metropolitanos",
  },
  {
    absoluteNum: 115,
    teamNum: 106,
    playerName: null,
    isSelected: false,
    team: "Metropolitanos",
  },
  {
    absoluteNum: 116,
    teamNum: 107,
    playerName: null,
    isSelected: false,
    team: "Metropolitanos",
  },
  {
    absoluteNum: 117,
    teamNum: 108,
    playerName: null,
    isSelected: false,
    team: "Metropolitanos",
  },
  {
    absoluteNum: 118,
    teamNum: 109,
    playerName: null,
    isSelected: false,
    team: "Metropolitanos",
  },
  {
    absoluteNum: 119,
    teamNum: 110,
    playerName: null,
    isSelected: false,
    team: "Metropolitanos",
  },
  {
    absoluteNum: 120,
    teamNum: 111,
    playerName: null,
    isSelected: false,
    team: "Metropolitanos",
  },
  {
    absoluteNum: 121,
    teamNum: 112,
    playerName: null,
    isSelected: false,
    team: "Metropolitanos",
  },
  {
    absoluteNum: 122,
    teamNum: 113,
    playerName: null,
    isSelected: false,
    team: "Metropolitanos",
  },
  {
    absoluteNum: 123,
    teamNum: 114,
    playerName: null,
    isSelected: false,
    team: "Metropolitanos",
  },
  {
    absoluteNum: 124,
    teamNum: 115,
    playerName: null,
    isSelected: false,
    team: "Metropolitanos",
  },
  {
    absoluteNum: 125,
    teamNum: 116,
    playerName: null,
    isSelected: false,
    team: "Metropolitanos",
  },
  {
    absoluteNum: 126,
    teamNum: 117,
    playerName: null,
    isSelected: false,
    team: "Metropolitanos",
  },
  {
    absoluteNum: 127,
    teamNum: 118,
    playerName: null,
    isSelected: false,
    team: "Metropolitanos",
  },
  {
    absoluteNum: 128,
    teamNum: 119,
    playerName: null,
    isSelected: false,
    team: "Metropolitanos",
  },
  {
    absoluteNum: 129,
    teamNum: 120,
    playerName: null,
    isSelected: false,
    team: "Nacional",
  },
  {
    absoluteNum: 130,
    teamNum: 121,
    playerName: null,
    isSelected: false,
    team: "Nacional",
  },
  {
    absoluteNum: 131,
    teamNum: 122,
    playerName: null,
    isSelected: false,
    team: "Nacional",
  },
  {
    absoluteNum: 132,
    teamNum: 123,
    playerName: null,
    isSelected: false,
    team: "Nacional",
  },
  {
    absoluteNum: 133,
    teamNum: 124,
    playerName: null,
    isSelected: false,
    team: "Nacional",
  },
  {
    absoluteNum: 134,
    teamNum: 125,
    playerName: null,
    isSelected: false,
    team: "Nacional",
  },
  {
    absoluteNum: 135,
    teamNum: 126,
    playerName: null,
    isSelected: false,
    team: "Nacional",
  },
  {
    absoluteNum: 136,
    teamNum: 127,
    playerName: null,
    isSelected: false,
    team: "Nacional",
  },
  {
    absoluteNum: 137,
    teamNum: 128,
    playerName: null,
    isSelected: false,
    team: "Nacional",
  },
  {
    absoluteNum: 138,
    teamNum: 129,
    playerName: null,
    isSelected: false,
    team: "Nacional",
  },
  {
    absoluteNum: 139,
    teamNum: 130,
    playerName: null,
    isSelected: false,
    team: "Nacional",
  },
  {
    absoluteNum: 140,
    teamNum: 131,
    playerName: null,
    isSelected: false,
    team: "Nacional",
  },
  {
    absoluteNum: 141,
    teamNum: 132,
    playerName: null,
    isSelected: false,
    team: "Nacional",
  },
  {
    absoluteNum: 142,
    teamNum: 133,
    playerName: null,
    isSelected: false,
    team: "Nacional",
  },
  {
    absoluteNum: 143,
    teamNum: 134,
    playerName: null,
    isSelected: false,
    team: "Nacional",
  },
  {
    absoluteNum: 144,
    teamNum: 135,
    playerName: null,
    isSelected: false,
    team: "Nacional",
  },
  {
    absoluteNum: 145,
    teamNum: 136,
    playerName: null,
    isSelected: false,
    team: "Nacional",
  },
  {
    absoluteNum: 146,
    teamNum: 137,
    playerName: null,
    isSelected: false,
    team: "Barcelona S.C.",
  },
  {
    absoluteNum: 147,
    teamNum: 138,
    playerName: null,
    isSelected: false,
    team: "Barcelona S.C.",
  },
  {
    absoluteNum: 148,
    teamNum: 139,
    playerName: null,
    isSelected: false,
    team: "Barcelona S.C.",
  },
  {
    absoluteNum: 149,
    teamNum: 140,
    playerName: null,
    isSelected: false,
    team: "Barcelona S.C.",
  },
  {
    absoluteNum: 150,
    teamNum: 141,
    playerName: null,
    isSelected: false,
    team: "Barcelona S.C.",
  },
  {
    absoluteNum: 151,
    teamNum: 142,
    playerName: null,
    isSelected: false,
    team: "Barcelona S.C.",
  },
  {
    absoluteNum: 152,
    teamNum: 143,
    playerName: null,
    isSelected: false,
    team: "Barcelona S.C.",
  },
  {
    absoluteNum: 153,
    teamNum: 144,
    playerName: null,
    isSelected: false,
    team: "Barcelona S.C.",
  },
  {
    absoluteNum: 154,
    teamNum: 145,
    playerName: null,
    isSelected: false,
    team: "Barcelona S.C.",
  },
  {
    absoluteNum: 155,
    teamNum: 146,
    playerName: null,
    isSelected: false,
    team: "Barcelona S.C.",
  },
  {
    absoluteNum: 156,
    teamNum: 147,
    playerName: null,
    isSelected: false,
    team: "Barcelona S.C.",
  },
  {
    absoluteNum: 157,
    teamNum: 148,
    playerName: null,
    isSelected: false,
    team: "Barcelona S.C.",
  },
  {
    absoluteNum: 158,
    teamNum: 149,
    playerName: null,
    isSelected: false,
    team: "Barcelona S.C.",
  },
  {
    absoluteNum: 159,
    teamNum: 150,
    playerName: null,
    isSelected: false,
    team: "Barcelona S.C.",
  },
  {
    absoluteNum: 160,
    teamNum: 151,
    playerName: null,
    isSelected: false,
    team: "Barcelona S.C.",
  },
  {
    absoluteNum: 161,
    teamNum: 152,
    playerName: null,
    isSelected: false,
    team: "Barcelona S.C.",
  },
  {
    absoluteNum: 162,
    teamNum: 153,
    playerName: null,
    isSelected: false,
    team: "Barcelona S.C.",
  },
  {
    absoluteNum: 163,
    teamNum: 154,
    playerName: null,
    isSelected: false,
    team: "Bolivar",
  },
  {
    absoluteNum: 164,
    teamNum: 155,
    playerName: null,
    isSelected: false,
    team: "Bolivar",
  },
  {
    absoluteNum: 165,
    teamNum: 156,
    playerName: null,
    isSelected: false,
    team: "Bolivar",
  },
  {
    absoluteNum: 166,
    teamNum: 157,
    playerName: null,
    isSelected: false,
    team: "Bolivar",
  },
  {
    absoluteNum: 167,
    teamNum: 158,
    playerName: null,
    isSelected: false,
    team: "Bolivar",
  },
  {
    absoluteNum: 168,
    teamNum: 159,
    playerName: null,
    isSelected: false,
    team: "Bolivar",
  },
  {
    absoluteNum: 169,
    teamNum: 160,
    playerName: null,
    isSelected: false,
    team: "Bolivar",
  },
  {
    absoluteNum: 170,
    teamNum: 161,
    playerName: null,
    isSelected: false,
    team: "Bolivar",
  },
  {
    absoluteNum: 171,
    teamNum: 162,
    playerName: null,
    isSelected: false,
    team: "Bolivar",
  },
  {
    absoluteNum: 172,
    teamNum: 163,
    playerName: null,
    isSelected: false,
    team: "Bolivar",
  },
  {
    absoluteNum: 173,
    teamNum: 164,
    playerName: null,
    isSelected: false,
    team: "Bolivar",
  },
  {
    absoluteNum: 174,
    teamNum: 165,
    playerName: null,
    isSelected: false,
    team: "Bolivar",
  },
  {
    absoluteNum: 175,
    teamNum: 166,
    playerName: null,
    isSelected: false,
    team: "Bolivar",
  },
  {
    absoluteNum: 176,
    teamNum: 167,
    playerName: null,
    isSelected: false,
    team: "Bolivar",
  },
  {
    absoluteNum: 177,
    teamNum: 168,
    playerName: null,
    isSelected: false,
    team: "Bolivar",
  },
  {
    absoluteNum: 178,
    teamNum: 169,
    playerName: null,
    isSelected: false,
    team: "Bolivar",
  },
  {
    absoluteNum: 179,
    teamNum: 170,
    playerName: null,
    isSelected: false,
    team: "Bolivar",
  },
  {
    absoluteNum: 180,
    teamNum: 171,
    playerName: null,
    isSelected: false,
    team: "Cerro porteño",
  },
  {
    absoluteNum: 181,
    teamNum: 172,
    playerName: null,
    isSelected: false,
    team: "Cerro porteño",
  },
  {
    absoluteNum: 182,
    teamNum: 173,
    playerName: null,
    isSelected: false,
    team: "Cerro porteño",
  },
  {
    absoluteNum: 183,
    teamNum: 174,
    playerName: null,
    isSelected: false,
    team: "Cerro porteño",
  },
  {
    absoluteNum: 184,
    teamNum: 175,
    playerName: null,
    isSelected: false,
    team: "Cerro porteño",
  },
  {
    absoluteNum: 185,
    teamNum: 176,
    playerName: null,
    isSelected: false,
    team: "Cerro porteño",
  },
  {
    absoluteNum: 186,
    teamNum: 177,
    playerName: null,
    isSelected: false,
    team: "Cerro porteño",
  },
  {
    absoluteNum: 187,
    teamNum: 178,
    playerName: null,
    isSelected: false,
    team: "Cerro porteño",
  },
  {
    absoluteNum: 188,
    teamNum: 179,
    playerName: null,
    isSelected: false,
    team: "Cerro porteño",
  },
  {
    absoluteNum: 189,
    teamNum: 180,
    playerName: null,
    isSelected: false,
    team: "Cerro porteño",
  },
  {
    absoluteNum: 190,
    teamNum: 181,
    playerName: null,
    isSelected: false,
    team: "Cerro porteño",
  },
  {
    absoluteNum: 191,
    teamNum: 182,
    playerName: null,
    isSelected: false,
    team: "Cerro porteño",
  },
  {
    absoluteNum: 192,
    teamNum: 183,
    playerName: null,
    isSelected: false,
    team: "Cerro porteño",
  },
  {
    absoluteNum: 193,
    teamNum: 184,
    playerName: null,
    isSelected: false,
    team: "Cerro porteño",
  },
  {
    absoluteNum: 194,
    teamNum: 185,
    playerName: null,
    isSelected: false,
    team: "Cerro porteño",
  },
  {
    absoluteNum: 195,
    teamNum: 186,
    playerName: null,
    isSelected: false,
    team: "Cerro porteño",
  },
  {
    absoluteNum: 196,
    teamNum: 187,
    playerName: null,
    isSelected: false,
    team: "Cerro porteño",
  },
  {
    absoluteNum: 197,
    teamNum: 188,
    playerName: null,
    isSelected: false,
    team: "Palmeiras",
  },
  {
    absoluteNum: 198,
    teamNum: 189,
    playerName: null,
    isSelected: false,
    team: "Palmeiras",
  },
  {
    absoluteNum: 199,
    teamNum: 190,
    playerName: null,
    isSelected: false,
    team: "Palmeiras",
  },
  {
    absoluteNum: 200,
    teamNum: 191,
    playerName: null,
    isSelected: false,
    team: "Palmeiras",
  },
  {
    absoluteNum: 201,
    teamNum: 192,
    playerName: null,
    isSelected: false,
    team: "Palmeiras",
  },
  {
    absoluteNum: 202,
    teamNum: 193,
    playerName: null,
    isSelected: false,
    team: "Palmeiras",
  },
  {
    absoluteNum: 203,
    teamNum: 194,
    playerName: null,
    isSelected: false,
    team: "Palmeiras",
  },
  {
    absoluteNum: 204,
    teamNum: 195,
    playerName: null,
    isSelected: false,
    team: "Palmeiras",
  },
  {
    absoluteNum: 205,
    teamNum: 196,
    playerName: null,
    isSelected: false,
    team: "Palmeiras",
  },
  {
    absoluteNum: 206,
    teamNum: 197,
    playerName: null,
    isSelected: false,
    team: "Palmeiras",
  },
  {
    absoluteNum: 207,
    teamNum: 198,
    playerName: null,
    isSelected: false,
    team: "Palmeiras",
  },
  {
    absoluteNum: 208,
    teamNum: 199,
    playerName: null,
    isSelected: false,
    team: "Palmeiras",
  },
  {
    absoluteNum: 209,
    teamNum: 200,
    playerName: null,
    isSelected: false,
    team: "Palmeiras",
  },
  {
    absoluteNum: 210,
    teamNum: 201,
    playerName: null,
    isSelected: false,
    team: "Palmeiras",
  },
  {
    absoluteNum: 211,
    teamNum: 202,
    playerName: null,
    isSelected: false,
    team: "Palmeiras",
  },
  {
    absoluteNum: 212,
    teamNum: 203,
    playerName: null,
    isSelected: false,
    team: "Palmeiras",
  },
  {
    absoluteNum: 213,
    teamNum: 204,
    playerName: null,
    isSelected: false,
    team: "Palmeiras",
  },
  {
    absoluteNum: 214,
    teamNum: 205,
    playerName: null,
    isSelected: false,
    team: "Fluminense",
  },
  {
    absoluteNum: 215,
    teamNum: 206,
    playerName: null,
    isSelected: false,
    team: "Fluminense",
  },
  {
    absoluteNum: 216,
    teamNum: 207,
    playerName: null,
    isSelected: false,
    team: "Fluminense",
  },
  {
    absoluteNum: 217,
    teamNum: 208,
    playerName: null,
    isSelected: false,
    team: "Fluminense",
  },
  {
    absoluteNum: 218,
    teamNum: 209,
    playerName: null,
    isSelected: false,
    team: "Fluminense",
  },
  {
    absoluteNum: 219,
    teamNum: 210,
    playerName: null,
    isSelected: false,
    team: "Fluminense",
  },
  {
    absoluteNum: 220,
    teamNum: 211,
    playerName: null,
    isSelected: false,
    team: "Fluminense",
  },
  {
    absoluteNum: 221,
    teamNum: 212,
    playerName: null,
    isSelected: false,
    team: "Fluminense",
  },
  {
    absoluteNum: 222,
    teamNum: 213,
    playerName: null,
    isSelected: false,
    team: "Fluminense",
  },
  {
    absoluteNum: 223,
    teamNum: 214,
    playerName: null,
    isSelected: false,
    team: "Fluminense",
  },
  {
    absoluteNum: 224,
    teamNum: 215,
    playerName: null,
    isSelected: false,
    team: "Fluminense",
  },
  {
    absoluteNum: 225,
    teamNum: 216,
    playerName: null,
    isSelected: false,
    team: "Fluminense",
  },
  {
    absoluteNum: 226,
    teamNum: 217,
    playerName: null,
    isSelected: false,
    team: "Fluminense",
  },
  {
    absoluteNum: 227,
    teamNum: 218,
    playerName: null,
    isSelected: false,
    team: "Fluminense",
  },
  {
    absoluteNum: 228,
    teamNum: 219,
    playerName: null,
    isSelected: false,
    team: "Fluminense",
  },
  {
    absoluteNum: 229,
    teamNum: 220,
    playerName: null,
    isSelected: false,
    team: "Fluminense",
  },
  {
    absoluteNum: 230,
    teamNum: 221,
    playerName: null,
    isSelected: false,
    team: "Fluminense",
  },
  {
    absoluteNum: 231,
    teamNum: 222,
    playerName: null,
    isSelected: false,
    team: "River Plate",
  },
  {
    absoluteNum: 232,
    teamNum: 223,
    playerName: null,
    isSelected: false,
    team: "River Plate",
  },
  {
    absoluteNum: 233,
    teamNum: 224,
    playerName: null,
    isSelected: false,
    team: "River Plate",
  },
  {
    absoluteNum: 234,
    teamNum: 225,
    playerName: null,
    isSelected: false,
    team: "River Plate",
  },
  {
    absoluteNum: 235,
    teamNum: 226,
    playerName: null,
    isSelected: false,
    team: "River Plate",
  },
  {
    absoluteNum: 236,
    teamNum: 227,
    playerName: null,
    isSelected: false,
    team: "River Plate",
  },
  {
    absoluteNum: 237,
    teamNum: 228,
    playerName: null,
    isSelected: false,
    team: "River Plate",
  },
  {
    absoluteNum: 238,
    teamNum: 229,
    playerName: null,
    isSelected: false,
    team: "River Plate",
  },
  {
    absoluteNum: 239,
    teamNum: 230,
    playerName: null,
    isSelected: false,
    team: "River Plate",
  },
  {
    absoluteNum: 240,
    teamNum: 231,
    playerName: null,
    isSelected: false,
    team: "River Plate",
  },
  {
    absoluteNum: 241,
    teamNum: 232,
    playerName: null,
    isSelected: false,
    team: "River Plate",
  },
  {
    absoluteNum: 242,
    teamNum: 233,
    playerName: null,
    isSelected: false,
    team: "River Plate",
  },
  {
    absoluteNum: 243,
    teamNum: 234,
    playerName: null,
    isSelected: false,
    team: "River Plate",
  },
  {
    absoluteNum: 244,
    teamNum: 235,
    playerName: null,
    isSelected: false,
    team: "River Plate",
  },
  {
    absoluteNum: 245,
    teamNum: 236,
    playerName: null,
    isSelected: false,
    team: "River Plate",
  },
  {
    absoluteNum: 246,
    teamNum: 237,
    playerName: null,
    isSelected: false,
    team: "River Plate",
  },
  {
    absoluteNum: 247,
    teamNum: 238,
    playerName: null,
    isSelected: false,
    team: "River Plate",
  },
  {
    absoluteNum: 248,
    teamNum: 239,
    playerName: null,
    isSelected: false,
    team: "Sporting Cristal",
  },
  {
    absoluteNum: 249,
    teamNum: 240,
    playerName: null,
    isSelected: false,
    team: "Sporting Cristal",
  },
  {
    absoluteNum: 250,
    teamNum: 241,
    playerName: null,
    isSelected: false,
    team: "Sporting Cristal",
  },
  {
    absoluteNum: 251,
    teamNum: 242,
    playerName: null,
    isSelected: false,
    team: "Sporting Cristal",
  },
  {
    absoluteNum: 252,
    teamNum: 243,
    playerName: null,
    isSelected: false,
    team: "Sporting Cristal",
  },
  {
    absoluteNum: 253,
    teamNum: 244,
    playerName: null,
    isSelected: false,
    team: "Sporting Cristal",
  },
  {
    absoluteNum: 254,
    teamNum: 245,
    playerName: null,
    isSelected: false,
    team: "Sporting Cristal",
  },
  {
    absoluteNum: 255,
    teamNum: 246,
    playerName: null,
    isSelected: false,
    team: "Sporting Cristal",
  },
  {
    absoluteNum: 256,
    teamNum: 247,
    playerName: null,
    isSelected: false,
    team: "Sporting Cristal",
  },
  {
    absoluteNum: 257,
    teamNum: 248,
    playerName: null,
    isSelected: false,
    team: "Sporting Cristal",
  },
  {
    absoluteNum: 258,
    teamNum: 249,
    playerName: null,
    isSelected: false,
    team: "Sporting Cristal",
  },
  {
    absoluteNum: 259,
    teamNum: 250,
    playerName: null,
    isSelected: false,
    team: "Sporting Cristal",
  },
  {
    absoluteNum: 260,
    teamNum: 251,
    playerName: null,
    isSelected: false,
    team: "Sporting Cristal",
  },
  {
    absoluteNum: 261,
    teamNum: 252,
    playerName: null,
    isSelected: false,
    team: "Sporting Cristal",
  },
  {
    absoluteNum: 262,
    teamNum: 253,
    playerName: null,
    isSelected: false,
    team: "Sporting Cristal",
  },
  {
    absoluteNum: 263,
    teamNum: 254,
    playerName: null,
    isSelected: false,
    team: "Sporting Cristal",
  },
  {
    absoluteNum: 264,
    teamNum: 255,
    playerName: null,
    isSelected: false,
    team: "Sporting Cristal",
  },
  {
    absoluteNum: 265,
    teamNum: 256,
    playerName: null,
    isSelected: false,
    team: "The Strongest",
  },
  {
    absoluteNum: 266,
    teamNum: 257,
    playerName: null,
    isSelected: false,
    team: "The Strongest",
  },
  {
    absoluteNum: 267,
    teamNum: 258,
    playerName: null,
    isSelected: false,
    team: "The Strongest",
  },
  {
    absoluteNum: 268,
    teamNum: 259,
    playerName: null,
    isSelected: false,
    team: "The Strongest",
  },
  {
    absoluteNum: 269,
    teamNum: 260,
    playerName: null,
    isSelected: false,
    team: "The Strongest",
  },
  {
    absoluteNum: 270,
    teamNum: 261,
    playerName: null,
    isSelected: false,
    team: "The Strongest",
  },
  {
    absoluteNum: 271,
    teamNum: 262,
    playerName: null,
    isSelected: false,
    team: "The Strongest",
  },
  {
    absoluteNum: 272,
    teamNum: 263,
    playerName: null,
    isSelected: false,
    team: "The Strongest",
  },
  {
    absoluteNum: 273,
    teamNum: 264,
    playerName: null,
    isSelected: false,
    team: "The Strongest",
  },
  {
    absoluteNum: 274,
    teamNum: 265,
    playerName: null,
    isSelected: false,
    team: "The Strongest",
  },
  {
    absoluteNum: 275,
    teamNum: 266,
    playerName: null,
    isSelected: false,
    team: "The Strongest",
  },
  {
    absoluteNum: 276,
    teamNum: 267,
    playerName: null,
    isSelected: false,
    team: "The Strongest",
  },
  {
    absoluteNum: 277,
    teamNum: 268,
    playerName: null,
    isSelected: false,
    team: "The Strongest",
  },
  {
    absoluteNum: 278,
    teamNum: 269,
    playerName: null,
    isSelected: false,
    team: "The Strongest",
  },
  {
    absoluteNum: 279,
    teamNum: 270,
    playerName: null,
    isSelected: false,
    team: "The Strongest",
  },
  {
    absoluteNum: 280,
    teamNum: 271,
    playerName: null,
    isSelected: false,
    team: "The Strongest",
  },
  {
    absoluteNum: 281,
    teamNum: 272,
    playerName: null,
    isSelected: false,
    team: "The Strongest",
  },
  {
    absoluteNum: 282,
    teamNum: 273,
    playerName: null,
    isSelected: false,
    team: "Argentinos Juniors",
  },
  {
    absoluteNum: 283,
    teamNum: 274,
    playerName: null,
    isSelected: false,
    team: "Argentinos Juniors",
  },
  {
    absoluteNum: 284,
    teamNum: 275,
    playerName: null,
    isSelected: false,
    team: "Argentinos Juniors",
  },
  {
    absoluteNum: 285,
    teamNum: 276,
    playerName: null,
    isSelected: false,
    team: "Argentinos Juniors",
  },
  {
    absoluteNum: 286,
    teamNum: 277,
    playerName: null,
    isSelected: false,
    team: "Argentinos Juniors",
  },
  {
    absoluteNum: 287,
    teamNum: 278,
    playerName: null,
    isSelected: false,
    team: "Argentinos Juniors",
  },
  {
    absoluteNum: 288,
    teamNum: 279,
    playerName: null,
    isSelected: false,
    team: "Argentinos Juniors",
  },
  {
    absoluteNum: 289,
    teamNum: 280,
    playerName: null,
    isSelected: false,
    team: "Argentinos Juniors",
  },
  {
    absoluteNum: 290,
    teamNum: 281,
    playerName: null,
    isSelected: false,
    team: "Argentinos Juniors",
  },
  {
    absoluteNum: 291,
    teamNum: 282,
    playerName: null,
    isSelected: false,
    team: "Argentinos Juniors",
  },
  {
    absoluteNum: 292,
    teamNum: 283,
    playerName: null,
    isSelected: false,
    team: "Argentinos Juniors",
  },
  {
    absoluteNum: 293,
    teamNum: 284,
    playerName: null,
    isSelected: false,
    team: "Argentinos Juniors",
  },
  {
    absoluteNum: 294,
    teamNum: 285,
    playerName: null,
    isSelected: false,
    team: "Argentinos Juniors",
  },
  {
    absoluteNum: 295,
    teamNum: 286,
    playerName: null,
    isSelected: false,
    team: "Argentinos Juniors",
  },
  {
    absoluteNum: 296,
    teamNum: 287,
    playerName: null,
    isSelected: false,
    team: "Argentinos Juniors",
  },
  {
    absoluteNum: 297,
    teamNum: 288,
    playerName: null,
    isSelected: false,
    team: "Argentinos Juniors",
  },
  {
    absoluteNum: 298,
    teamNum: 289,
    playerName: null,
    isSelected: false,
    team: "Argentinos Juniors",
  },
  {
    absoluteNum: 299,
    teamNum: 290,
    playerName: null,
    isSelected: false,
    team: "Corinthians",
  },
  {
    absoluteNum: 300,
    teamNum: 291,
    playerName: null,
    isSelected: false,
    team: "Corinthians",
  },
  {
    absoluteNum: 301,
    teamNum: 292,
    playerName: null,
    isSelected: false,
    team: "Corinthians",
  },
  {
    absoluteNum: 302,
    teamNum: 293,
    playerName: null,
    isSelected: false,
    team: "Corinthians",
  },
  {
    absoluteNum: 303,
    teamNum: 294,
    playerName: null,
    isSelected: false,
    team: "Corinthians",
  },
  {
    absoluteNum: 304,
    teamNum: 295,
    playerName: null,
    isSelected: false,
    team: "Corinthians",
  },
  {
    absoluteNum: 305,
    teamNum: 296,
    playerName: null,
    isSelected: false,
    team: "Corinthians",
  },
  {
    absoluteNum: 306,
    teamNum: 297,
    playerName: null,
    isSelected: false,
    team: "Corinthians",
  },
  {
    absoluteNum: 307,
    teamNum: 298,
    playerName: null,
    isSelected: false,
    team: "Corinthians",
  },
  {
    absoluteNum: 308,
    teamNum: 299,
    playerName: null,
    isSelected: false,
    team: "Corinthians",
  },
  {
    absoluteNum: 309,
    teamNum: 300,
    playerName: null,
    isSelected: false,
    team: "Corinthians",
  },
  {
    absoluteNum: 310,
    teamNum: 301,
    playerName: null,
    isSelected: false,
    team: "Corinthians",
  },
  {
    absoluteNum: 311,
    teamNum: 302,
    playerName: null,
    isSelected: false,
    team: "Corinthians",
  },
  {
    absoluteNum: 312,
    teamNum: 303,
    playerName: null,
    isSelected: false,
    team: "Corinthians",
  },
  {
    absoluteNum: 313,
    teamNum: 304,
    playerName: null,
    isSelected: false,
    team: "Corinthians",
  },
  {
    absoluteNum: 314,
    teamNum: 305,
    playerName: null,
    isSelected: false,
    team: "Corinthians",
  },
  {
    absoluteNum: 315,
    teamNum: 306,
    playerName: null,
    isSelected: false,
    team: "Corinthians",
  },
  {
    absoluteNum: 316,
    teamNum: 307,
    playerName: null,
    isSelected: false,
    team: "Independiente del Valle",
  },
  {
    absoluteNum: 317,
    teamNum: 308,
    playerName: null,
    isSelected: false,
    team: "Independiente del Valle",
  },
  {
    absoluteNum: 318,
    teamNum: 309,
    playerName: null,
    isSelected: false,
    team: "Independiente del Valle",
  },
  {
    absoluteNum: 319,
    teamNum: 310,
    playerName: null,
    isSelected: false,
    team: "Independiente del Valle",
  },
  {
    absoluteNum: 320,
    teamNum: 311,
    playerName: null,
    isSelected: false,
    team: "Independiente del Valle",
  },
  {
    absoluteNum: 321,
    teamNum: 312,
    playerName: null,
    isSelected: false,
    team: "Independiente del Valle",
  },
  {
    absoluteNum: 322,
    teamNum: 313,
    playerName: null,
    isSelected: false,
    team: "Independiente del Valle",
  },
  {
    absoluteNum: 323,
    teamNum: 314,
    playerName: null,
    isSelected: false,
    team: "Independiente del Valle",
  },
  {
    absoluteNum: 324,
    teamNum: 315,
    playerName: null,
    isSelected: false,
    team: "Independiente del Valle",
  },
  {
    absoluteNum: 325,
    teamNum: 316,
    playerName: null,
    isSelected: false,
    team: "Independiente del Valle",
  },
  {
    absoluteNum: 326,
    teamNum: 317,
    playerName: null,
    isSelected: false,
    team: "Independiente del Valle",
  },
  {
    absoluteNum: 327,
    teamNum: 318,
    playerName: null,
    isSelected: false,
    team: "Independiente del Valle",
  },
  {
    absoluteNum: 328,
    teamNum: 319,
    playerName: null,
    isSelected: false,
    team: "Independiente del Valle",
  },
  {
    absoluteNum: 329,
    teamNum: 320,
    playerName: null,
    isSelected: false,
    team: "Independiente del Valle",
  },
  {
    absoluteNum: 330,
    teamNum: 321,
    playerName: null,
    isSelected: false,
    team: "Independiente del Valle",
  },
  {
    absoluteNum: 331,
    teamNum: 322,
    playerName: null,
    isSelected: false,
    team: "Independiente del Valle",
  },
  {
    absoluteNum: 332,
    teamNum: 323,
    playerName: null,
    isSelected: false,
    team: "Independiente del Valle",
  },
  {
    absoluteNum: 333,
    teamNum: 324,
    playerName: null,
    isSelected: false,
    team: "Liverpool",
  },
  {
    absoluteNum: 334,
    teamNum: 325,
    playerName: null,
    isSelected: false,
    team: "Liverpool",
  },
  {
    absoluteNum: 335,
    teamNum: 326,
    playerName: null,
    isSelected: false,
    team: "Liverpool",
  },
  {
    absoluteNum: 336,
    teamNum: 327,
    playerName: null,
    isSelected: false,
    team: "Liverpool",
  },
  {
    absoluteNum: 337,
    teamNum: 328,
    playerName: null,
    isSelected: false,
    team: "Liverpool",
  },
  {
    absoluteNum: 338,
    teamNum: 329,
    playerName: null,
    isSelected: false,
    team: "Liverpool",
  },
  {
    absoluteNum: 339,
    teamNum: 330,
    playerName: null,
    isSelected: false,
    team: "Liverpool",
  },
  {
    absoluteNum: 340,
    teamNum: 331,
    playerName: null,
    isSelected: false,
    team: "Liverpool",
  },
  {
    absoluteNum: 341,
    teamNum: 332,
    playerName: null,
    isSelected: false,
    team: "Liverpool",
  },
  {
    absoluteNum: 342,
    teamNum: 333,
    playerName: null,
    isSelected: false,
    team: "Liverpool",
  },
  {
    absoluteNum: 343,
    teamNum: 334,
    playerName: null,
    isSelected: false,
    team: "Liverpool",
  },
  {
    absoluteNum: 344,
    teamNum: 335,
    playerName: null,
    isSelected: false,
    team: "Liverpool",
  },
  {
    absoluteNum: 345,
    teamNum: 336,
    playerName: null,
    isSelected: false,
    team: "Liverpool",
  },
  {
    absoluteNum: 346,
    teamNum: 337,
    playerName: null,
    isSelected: false,
    team: "Liverpool",
  },
  {
    absoluteNum: 347,
    teamNum: 338,
    playerName: null,
    isSelected: false,
    team: "Liverpool",
  },
  {
    absoluteNum: 348,
    teamNum: 339,
    playerName: null,
    isSelected: false,
    team: "Liverpool",
  },
  {
    absoluteNum: 349,
    teamNum: 340,
    playerName: null,
    isSelected: false,
    team: "Liverpool",
  },
  {
    absoluteNum: 350,
    teamNum: 341,
    playerName: null,
    isSelected: false,
    team: "Boca jrs.",
  },
  {
    absoluteNum: 351,
    teamNum: 342,
    playerName: null,
    isSelected: false,
    team: "Boca jrs.",
  },
  {
    absoluteNum: 352,
    teamNum: 343,
    playerName: null,
    isSelected: false,
    team: "Boca jrs.",
  },
  {
    absoluteNum: 353,
    teamNum: 344,
    playerName: null,
    isSelected: false,
    team: "Boca jrs.",
  },
  {
    absoluteNum: 354,
    teamNum: 345,
    playerName: null,
    isSelected: false,
    team: "Boca jrs.",
  },
  {
    absoluteNum: 355,
    teamNum: 346,
    playerName: null,
    isSelected: false,
    team: "Boca jrs.",
  },
  {
    absoluteNum: 356,
    teamNum: 347,
    playerName: null,
    isSelected: false,
    team: "Boca jrs.",
  },
  {
    absoluteNum: 357,
    teamNum: 348,
    playerName: null,
    isSelected: false,
    team: "Boca jrs.",
  },
  {
    absoluteNum: 358,
    teamNum: 349,
    playerName: null,
    isSelected: false,
    team: "Boca jrs.",
  },
  {
    absoluteNum: 359,
    teamNum: 350,
    playerName: null,
    isSelected: false,
    team: "Boca jrs.",
  },
  {
    absoluteNum: 360,
    teamNum: 351,
    playerName: null,
    isSelected: false,
    team: "Boca jrs.",
  },
  {
    absoluteNum: 361,
    teamNum: 352,
    playerName: null,
    isSelected: false,
    team: "Boca jrs.",
  },
  {
    absoluteNum: 362,
    teamNum: 353,
    playerName: null,
    isSelected: false,
    team: "Boca jrs.",
  },
  {
    absoluteNum: 363,
    teamNum: 354,
    playerName: null,
    isSelected: false,
    team: "Boca jrs.",
  },
  {
    absoluteNum: 364,
    teamNum: 355,
    playerName: null,
    isSelected: false,
    team: "Boca jrs.",
  },
  {
    absoluteNum: 365,
    teamNum: 356,
    playerName: null,
    isSelected: false,
    team: "Boca jrs.",
  },
  {
    absoluteNum: 366,
    teamNum: 357,
    playerName: null,
    isSelected: false,
    team: "Boca jrs.",
  },
  {
    absoluteNum: 367,
    teamNum: 358,
    playerName: null,
    isSelected: false,
    team: "Colo-colo",
  },
  {
    absoluteNum: 368,
    teamNum: 359,
    playerName: null,
    isSelected: false,
    team: "Colo-colo",
  },
  {
    absoluteNum: 369,
    teamNum: 360,
    playerName: null,
    isSelected: false,
    team: "Colo-colo",
  },
  {
    absoluteNum: 370,
    teamNum: 361,
    playerName: null,
    isSelected: false,
    team: "Colo-colo",
  },
  {
    absoluteNum: 371,
    teamNum: 362,
    playerName: null,
    isSelected: false,
    team: "Colo-colo",
  },
  {
    absoluteNum: 372,
    teamNum: 363,
    playerName: null,
    isSelected: false,
    team: "Colo-colo",
  },
  {
    absoluteNum: 373,
    teamNum: 364,
    playerName: null,
    isSelected: false,
    team: "Colo-colo",
  },
  {
    absoluteNum: 374,
    teamNum: 365,
    playerName: null,
    isSelected: false,
    team: "Colo-colo",
  },
  {
    absoluteNum: 375,
    teamNum: 366,
    playerName: null,
    isSelected: false,
    team: "Colo-colo",
  },
  {
    absoluteNum: 376,
    teamNum: 367,
    playerName: null,
    isSelected: false,
    team: "Colo-colo",
  },
  {
    absoluteNum: 377,
    teamNum: 368,
    playerName: null,
    isSelected: false,
    team: "Colo-colo",
  },
  {
    absoluteNum: 378,
    teamNum: 369,
    playerName: null,
    isSelected: false,
    team: "Colo-colo",
  },
  {
    absoluteNum: 379,
    teamNum: 370,
    playerName: null,
    isSelected: false,
    team: "Colo-colo",
  },
  {
    absoluteNum: 380,
    teamNum: 371,
    playerName: null,
    isSelected: false,
    team: "Colo-colo",
  },
  {
    absoluteNum: 381,
    teamNum: 372,
    playerName: null,
    isSelected: false,
    team: "Colo-colo",
  },
  {
    absoluteNum: 382,
    teamNum: 373,
    playerName: null,
    isSelected: false,
    team: "Colo-colo",
  },
  {
    absoluteNum: 383,
    teamNum: 374,
    playerName: null,
    isSelected: false,
    team: "Colo-colo",
  },
  {
    absoluteNum: 384,
    teamNum: 375,
    playerName: null,
    isSelected: false,
    team: "Monagas",
  },
  {
    absoluteNum: 385,
    teamNum: 376,
    playerName: null,
    isSelected: false,
    team: "Monagas",
  },
  {
    absoluteNum: 386,
    teamNum: 377,
    playerName: null,
    isSelected: false,
    team: "Monagas",
  },
  {
    absoluteNum: 387,
    teamNum: 378,
    playerName: null,
    isSelected: false,
    team: "Monagas",
  },
  {
    absoluteNum: 388,
    teamNum: 379,
    playerName: null,
    isSelected: false,
    team: "Monagas",
  },
  {
    absoluteNum: 389,
    teamNum: 380,
    playerName: null,
    isSelected: false,
    team: "Monagas",
  },
  {
    absoluteNum: 390,
    teamNum: 381,
    playerName: null,
    isSelected: false,
    team: "Monagas",
  },
  {
    absoluteNum: 391,
    teamNum: 382,
    playerName: null,
    isSelected: false,
    team: "Monagas",
  },
  {
    absoluteNum: 392,
    teamNum: 383,
    playerName: null,
    isSelected: false,
    team: "Monagas",
  },
  {
    absoluteNum: 393,
    teamNum: 384,
    playerName: null,
    isSelected: false,
    team: "Monagas",
  },
  {
    absoluteNum: 394,
    teamNum: 385,
    playerName: null,
    isSelected: false,
    team: "Monagas",
  },
  {
    absoluteNum: 395,
    teamNum: 386,
    playerName: null,
    isSelected: false,
    team: "Monagas",
  },
  {
    absoluteNum: 396,
    teamNum: 387,
    playerName: null,
    isSelected: false,
    team: "Monagas",
  },
  {
    absoluteNum: 397,
    teamNum: 388,
    playerName: null,
    isSelected: false,
    team: "Monagas",
  },
  {
    absoluteNum: 398,
    teamNum: 389,
    playerName: null,
    isSelected: false,
    team: "Monagas",
  },
  {
    absoluteNum: 399,
    teamNum: 390,
    playerName: null,
    isSelected: false,
    team: "Monagas",
  },
  {
    absoluteNum: 400,
    teamNum: 391,
    playerName: null,
    isSelected: false,
    team: "Monagas",
  },
  {
    absoluteNum: 401,
    teamNum: 392,
    playerName: null,
    isSelected: false,
    team: "Deportivo Pereira",
  },
  {
    absoluteNum: 402,
    teamNum: 393,
    playerName: null,
    isSelected: false,
    team: "Deportivo Pereira",
  },
  {
    absoluteNum: 403,
    teamNum: 394,
    playerName: null,
    isSelected: false,
    team: "Deportivo Pereira",
  },
  {
    absoluteNum: 404,
    teamNum: 395,
    playerName: null,
    isSelected: false,
    team: "Deportivo Pereira",
  },
  {
    absoluteNum: 405,
    teamNum: 396,
    playerName: null,
    isSelected: false,
    team: "Deportivo Pereira",
  },
  {
    absoluteNum: 406,
    teamNum: 397,
    playerName: null,
    isSelected: false,
    team: "Deportivo Pereira",
  },
  {
    absoluteNum: 407,
    teamNum: 398,
    playerName: null,
    isSelected: false,
    team: "Deportivo Pereira",
  },
  {
    absoluteNum: 408,
    teamNum: 399,
    playerName: null,
    isSelected: false,
    team: "Deportivo Pereira",
  },
  {
    absoluteNum: 409,
    teamNum: 400,
    playerName: null,
    isSelected: false,
    team: "Deportivo Pereira",
  },
  {
    absoluteNum: 410,
    teamNum: 401,
    playerName: null,
    isSelected: false,
    team: "Deportivo Pereira",
  },
  {
    absoluteNum: 411,
    teamNum: 402,
    playerName: null,
    isSelected: false,
    team: "Deportivo Pereira",
  },
  {
    absoluteNum: 412,
    teamNum: 403,
    playerName: null,
    isSelected: false,
    team: "Deportivo Pereira",
  },
  {
    absoluteNum: 413,
    teamNum: 404,
    playerName: null,
    isSelected: false,
    team: "Deportivo Pereira",
  },
  {
    absoluteNum: 414,
    teamNum: 405,
    playerName: null,
    isSelected: false,
    team: "Deportivo Pereira",
  },
  {
    absoluteNum: 415,
    teamNum: 406,
    playerName: null,
    isSelected: false,
    team: "Deportivo Pereira",
  },
  {
    absoluteNum: 416,
    teamNum: 407,
    playerName: null,
    isSelected: false,
    team: "Deportivo Pereira",
  },
  {
    absoluteNum: 417,
    teamNum: 408,
    playerName: null,
    isSelected: false,
    team: "Deportivo Pereira",
  },
  {
    absoluteNum: 418,
    teamNum: 409,
    playerName: null,
    isSelected: false,
    team: "Alianza Lima",
  },
  {
    absoluteNum: 419,
    teamNum: 410,
    playerName: null,
    isSelected: false,
    team: "Alianza Lima",
  },
  {
    absoluteNum: 420,
    teamNum: 411,
    playerName: null,
    isSelected: false,
    team: "Alianza Lima",
  },
  {
    absoluteNum: 421,
    teamNum: 412,
    playerName: null,
    isSelected: false,
    team: "Alianza Lima",
  },
  {
    absoluteNum: 422,
    teamNum: 413,
    playerName: null,
    isSelected: false,
    team: "Alianza Lima",
  },
  {
    absoluteNum: 423,
    teamNum: 414,
    playerName: null,
    isSelected: false,
    team: "Alianza Lima",
  },
  {
    absoluteNum: 424,
    teamNum: 415,
    playerName: null,
    isSelected: false,
    team: "Alianza Lima",
  },
  {
    absoluteNum: 425,
    teamNum: 416,
    playerName: null,
    isSelected: false,
    team: "Alianza Lima",
  },
  {
    absoluteNum: 426,
    teamNum: 417,
    playerName: null,
    isSelected: false,
    team: "Alianza Lima",
  },
  {
    absoluteNum: 427,
    teamNum: 418,
    playerName: null,
    isSelected: false,
    team: "Alianza Lima",
  },
  {
    absoluteNum: 428,
    teamNum: 419,
    playerName: null,
    isSelected: false,
    team: "Alianza Lima",
  },
  {
    absoluteNum: 429,
    teamNum: 420,
    playerName: null,
    isSelected: false,
    team: "Alianza Lima",
  },
  {
    absoluteNum: 430,
    teamNum: 421,
    playerName: null,
    isSelected: false,
    team: "Alianza Lima",
  },
  {
    absoluteNum: 431,
    teamNum: 422,
    playerName: null,
    isSelected: false,
    team: "Alianza Lima",
  },
  {
    absoluteNum: 432,
    teamNum: 423,
    playerName: null,
    isSelected: false,
    team: "Alianza Lima",
  },
  {
    absoluteNum: 433,
    teamNum: 424,
    playerName: null,
    isSelected: false,
    team: "Alianza Lima",
  },
  {
    absoluteNum: 434,
    teamNum: 425,
    playerName: null,
    isSelected: false,
    team: "Alianza Lima",
  },
  {
    absoluteNum: 435,
    teamNum: 426,
    playerName: null,
    isSelected: false,
    team: "Atlético Paranaense",
  },
  {
    absoluteNum: 436,
    teamNum: 427,
    playerName: null,
    isSelected: false,
    team: "Atlético Paranaense",
  },
  {
    absoluteNum: 437,
    teamNum: 428,
    playerName: null,
    isSelected: false,
    team: "Atlético Paranaense",
  },
  {
    absoluteNum: 438,
    teamNum: 429,
    playerName: null,
    isSelected: false,
    team: "Atlético Paranaense",
  },
  {
    absoluteNum: 439,
    teamNum: 430,
    playerName: null,
    isSelected: false,
    team: "Atlético Paranaense",
  },
  {
    absoluteNum: 440,
    teamNum: 431,
    playerName: null,
    isSelected: false,
    team: "Atlético Paranaense",
  },
  {
    absoluteNum: 441,
    teamNum: 432,
    playerName: null,
    isSelected: false,
    team: "Atlético Paranaense",
  },
  {
    absoluteNum: 442,
    teamNum: 433,
    playerName: null,
    isSelected: false,
    team: "Atlético Paranaense",
  },
  {
    absoluteNum: 443,
    teamNum: 434,
    playerName: null,
    isSelected: false,
    team: "Atlético Paranaense",
  },
  {
    absoluteNum: 444,
    teamNum: 435,
    playerName: null,
    isSelected: false,
    team: "Atlético Paranaense",
  },
  {
    absoluteNum: 445,
    teamNum: 436,
    playerName: null,
    isSelected: false,
    team: "Atlético Paranaense",
  },
  {
    absoluteNum: 446,
    teamNum: 437,
    playerName: null,
    isSelected: false,
    team: "Atlético Paranaense",
  },
  {
    absoluteNum: 447,
    teamNum: 438,
    playerName: null,
    isSelected: false,
    team: "Atlético Paranaense",
  },
  {
    absoluteNum: 448,
    teamNum: 439,
    playerName: null,
    isSelected: false,
    team: "Atlético Paranaense",
  },
  {
    absoluteNum: 449,
    teamNum: 440,
    playerName: null,
    isSelected: false,
    team: "Atlético Paranaense",
  },
  {
    absoluteNum: 450,
    teamNum: 441,
    playerName: null,
    isSelected: false,
    team: "Atlético Paranaense",
  },
  {
    absoluteNum: 451,
    teamNum: 442,
    playerName: null,
    isSelected: false,
    team: "Atlético Paranaense",
  },
  {
    absoluteNum: 452,
    teamNum: 443,
    playerName: null,
    isSelected: false,
    team: "Atlético Mineiro",
  },
  {
    absoluteNum: 453,
    teamNum: 444,
    playerName: null,
    isSelected: false,
    team: "Atlético Mineiro",
  },
  {
    absoluteNum: 454,
    teamNum: 445,
    playerName: null,
    isSelected: false,
    team: "Atlético Mineiro",
  },
  {
    absoluteNum: 455,
    teamNum: 446,
    playerName: null,
    isSelected: false,
    team: "Atlético Mineiro",
  },
  {
    absoluteNum: 456,
    teamNum: 447,
    playerName: null,
    isSelected: false,
    team: "Atlético Mineiro",
  },
  {
    absoluteNum: 457,
    teamNum: 448,
    playerName: null,
    isSelected: false,
    team: "Atlético Mineiro",
  },
  {
    absoluteNum: 458,
    teamNum: 449,
    playerName: null,
    isSelected: false,
    team: "Atlético Mineiro",
  },
  {
    absoluteNum: 459,
    teamNum: 450,
    playerName: null,
    isSelected: false,
    team: "Atlético Mineiro",
  },
  {
    absoluteNum: 460,
    teamNum: 451,
    playerName: null,
    isSelected: false,
    team: "Atlético Mineiro",
  },
  {
    absoluteNum: 461,
    teamNum: 452,
    playerName: null,
    isSelected: false,
    team: "Atlético Mineiro",
  },
  {
    absoluteNum: 462,
    teamNum: 453,
    playerName: null,
    isSelected: false,
    team: "Atlético Mineiro",
  },
  {
    absoluteNum: 463,
    teamNum: 454,
    playerName: null,
    isSelected: false,
    team: "Atlético Mineiro",
  },
  {
    absoluteNum: 464,
    teamNum: 455,
    playerName: null,
    isSelected: false,
    team: "Atlético Mineiro",
  },
  {
    absoluteNum: 465,
    teamNum: 456,
    playerName: null,
    isSelected: false,
    team: "Atlético Mineiro",
  },
  {
    absoluteNum: 466,
    teamNum: 457,
    playerName: null,
    isSelected: false,
    team: "Atlético Mineiro",
  },
  {
    absoluteNum: 467,
    teamNum: 458,
    playerName: null,
    isSelected: false,
    team: "Atlético Mineiro",
  },
  {
    absoluteNum: 468,
    teamNum: 459,
    playerName: null,
    isSelected: false,
    team: "Atlético Mineiro",
  },
  {
    absoluteNum: 469,
    teamNum: 460,
    playerName: null,
    isSelected: false,
    team: "Libertad",
  },
  {
    absoluteNum: 470,
    teamNum: 461,
    playerName: null,
    isSelected: false,
    team: "Libertad",
  },
  {
    absoluteNum: 471,
    teamNum: 462,
    playerName: null,
    isSelected: false,
    team: "Libertad",
  },
  {
    absoluteNum: 472,
    teamNum: 463,
    playerName: null,
    isSelected: false,
    team: "Libertad",
  },
  {
    absoluteNum: 473,
    teamNum: 464,
    playerName: null,
    isSelected: false,
    team: "Libertad",
  },
  {
    absoluteNum: 474,
    teamNum: 465,
    playerName: null,
    isSelected: false,
    team: "Libertad",
  },
  {
    absoluteNum: 475,
    teamNum: 466,
    playerName: null,
    isSelected: false,
    team: "Libertad",
  },
  {
    absoluteNum: 476,
    teamNum: 467,
    playerName: null,
    isSelected: false,
    team: "Libertad",
  },
  {
    absoluteNum: 477,
    teamNum: 468,
    playerName: null,
    isSelected: false,
    team: "Libertad",
  },
  {
    absoluteNum: 478,
    teamNum: 469,
    playerName: null,
    isSelected: false,
    team: "Libertad",
  },
  {
    absoluteNum: 479,
    teamNum: 470,
    playerName: null,
    isSelected: false,
    team: "Libertad",
  },
  {
    absoluteNum: 480,
    teamNum: 471,
    playerName: null,
    isSelected: false,
    team: "Libertad",
  },
  {
    absoluteNum: 481,
    teamNum: 472,
    playerName: null,
    isSelected: false,
    team: "Libertad",
  },
  {
    absoluteNum: 482,
    teamNum: 473,
    playerName: null,
    isSelected: false,
    team: "Libertad",
  },
  {
    absoluteNum: 483,
    teamNum: 474,
    playerName: null,
    isSelected: false,
    team: "Libertad",
  },
  {
    absoluteNum: 484,
    teamNum: 475,
    playerName: null,
    isSelected: false,
    team: "Libertad",
  },
  {
    absoluteNum: 485,
    teamNum: 476,
    playerName: null,
    isSelected: false,
    team: "Libertad",
  },
  {
    absoluteNum: 486,
    teamNum: 477,
    playerName: null,
    isSelected: false,
    team: "Atlético Nacional",
  },
  {
    absoluteNum: 487,
    teamNum: 478,
    playerName: null,
    isSelected: false,
    team: "Atlético Nacional",
  },
  {
    absoluteNum: 488,
    teamNum: 479,
    playerName: null,
    isSelected: false,
    team: "Atlético Nacional",
  },
  {
    absoluteNum: 489,
    teamNum: 480,
    playerName: null,
    isSelected: false,
    team: "Atlético Nacional",
  },
  {
    absoluteNum: 490,
    teamNum: 481,
    playerName: null,
    isSelected: false,
    team: "Atlético Nacional",
  },
  {
    absoluteNum: 491,
    teamNum: 482,
    playerName: null,
    isSelected: false,
    team: "Atlético Nacional",
  },
  {
    absoluteNum: 492,
    teamNum: 483,
    playerName: null,
    isSelected: false,
    team: "Atlético Nacional",
  },
  {
    absoluteNum: 493,
    teamNum: 484,
    playerName: null,
    isSelected: false,
    team: "Atlético Nacional",
  },
  {
    absoluteNum: 494,
    teamNum: 485,
    playerName: null,
    isSelected: false,
    team: "Atlético Nacional",
  },
  {
    absoluteNum: 495,
    teamNum: 486,
    playerName: null,
    isSelected: false,
    team: "Atlético Nacional",
  },
  {
    absoluteNum: 496,
    teamNum: 487,
    playerName: null,
    isSelected: false,
    team: "Atlético Nacional",
  },
  {
    absoluteNum: 497,
    teamNum: 488,
    playerName: null,
    isSelected: false,
    team: "Atlético Nacional",
  },
  {
    absoluteNum: 498,
    teamNum: 489,
    playerName: null,
    isSelected: false,
    team: "Atlético Nacional",
  },
  {
    absoluteNum: 499,
    teamNum: 490,
    playerName: null,
    isSelected: false,
    team: "Atlético Nacional",
  },
  {
    absoluteNum: 500,
    teamNum: 491,
    playerName: null,
    isSelected: false,
    team: "Atlético Nacional",
  },
  {
    absoluteNum: 501,
    teamNum: 492,
    playerName: null,
    isSelected: false,
    team: "Atlético Nacional",
  },
  {
    absoluteNum: 502,
    teamNum: 493,
    playerName: null,
    isSelected: false,
    team: "Atlético Nacional",
  },
  {
    absoluteNum: 503,
    teamNum: 494,
    playerName: null,
    isSelected: false,
    team: "Melgar",
  },
  {
    absoluteNum: 504,
    teamNum: 495,
    playerName: null,
    isSelected: false,
    team: "Melgar",
  },
  {
    absoluteNum: 505,
    teamNum: 496,
    playerName: null,
    isSelected: false,
    team: "Melgar",
  },
  {
    absoluteNum: 506,
    teamNum: 497,
    playerName: null,
    isSelected: false,
    team: "Melgar",
  },
  {
    absoluteNum: 507,
    teamNum: 498,
    playerName: null,
    isSelected: false,
    team: "Melgar",
  },
  {
    absoluteNum: 508,
    teamNum: 499,
    playerName: null,
    isSelected: false,
    team: "Melgar",
  },
  {
    absoluteNum: 509,
    teamNum: 500,
    playerName: null,
    isSelected: false,
    team: "Melgar",
  },
  {
    absoluteNum: 510,
    teamNum: 501,
    playerName: null,
    isSelected: false,
    team: "Melgar",
  },
  {
    absoluteNum: 511,
    teamNum: 502,
    playerName: null,
    isSelected: false,
    team: "Melgar",
  },
  {
    absoluteNum: 512,
    teamNum: 503,
    playerName: null,
    isSelected: false,
    team: "Melgar",
  },
  {
    absoluteNum: 513,
    teamNum: 504,
    playerName: null,
    isSelected: false,
    team: "Melgar",
  },
  {
    absoluteNum: 514,
    teamNum: 505,
    playerName: null,
    isSelected: false,
    team: "Melgar",
  },
  {
    absoluteNum: 515,
    teamNum: 506,
    playerName: null,
    isSelected: false,
    team: "Melgar",
  },
  {
    absoluteNum: 516,
    teamNum: 507,
    playerName: null,
    isSelected: false,
    team: "Melgar",
  },
  {
    absoluteNum: 517,
    teamNum: 508,
    playerName: null,
    isSelected: false,
    team: "Melgar",
  },
  {
    absoluteNum: 518,
    teamNum: 509,
    playerName: null,
    isSelected: false,
    team: "Melgar",
  },
  {
    absoluteNum: 519,
    teamNum: 510,
    playerName: null,
    isSelected: false,
    team: "Melgar",
  },
  {
    absoluteNum: 520,
    teamNum: 511,
    playerName: null,
    isSelected: false,
    team: "Olimpia",
  },
  {
    absoluteNum: 521,
    teamNum: 512,
    playerName: null,
    isSelected: false,
    team: "Olimpia",
  },
  {
    absoluteNum: 522,
    teamNum: 513,
    playerName: null,
    isSelected: false,
    team: "Olimpia",
  },
  {
    absoluteNum: 523,
    teamNum: 514,
    playerName: null,
    isSelected: false,
    team: "Olimpia",
  },
  {
    absoluteNum: 524,
    teamNum: 515,
    playerName: null,
    isSelected: false,
    team: "Olimpia",
  },
  {
    absoluteNum: 525,
    teamNum: 516,
    playerName: null,
    isSelected: false,
    team: "Olimpia",
  },
  {
    absoluteNum: 526,
    teamNum: 517,
    playerName: null,
    isSelected: false,
    team: "Olimpia",
  },
  {
    absoluteNum: 527,
    teamNum: 518,
    playerName: null,
    isSelected: false,
    team: "Olimpia",
  },
  {
    absoluteNum: 528,
    teamNum: 519,
    playerName: null,
    isSelected: false,
    team: "Olimpia",
  },
  {
    absoluteNum: 529,
    teamNum: 520,
    playerName: null,
    isSelected: false,
    team: "Olimpia",
  },
  {
    absoluteNum: 530,
    teamNum: 521,
    playerName: null,
    isSelected: false,
    team: "Olimpia",
  },
  {
    absoluteNum: 531,
    teamNum: 522,
    playerName: null,
    isSelected: false,
    team: "Olimpia",
  },
  {
    absoluteNum: 532,
    teamNum: 523,
    playerName: null,
    isSelected: false,
    team: "Olimpia",
  },
  {
    absoluteNum: 533,
    teamNum: 524,
    playerName: null,
    isSelected: false,
    team: "Olimpia",
  },
  {
    absoluteNum: 534,
    teamNum: 525,
    playerName: null,
    isSelected: false,
    team: "Olimpia",
  },
  {
    absoluteNum: 535,
    teamNum: 526,
    playerName: null,
    isSelected: false,
    team: "Olimpia",
  },
  {
    absoluteNum: 536,
    teamNum: 527,
    playerName: null,
    isSelected: false,
    team: "Olimpia",
  },
  {
    absoluteNum: 537,
    teamNum: 528,
    playerName: null,
    isSelected: false,
    team: "Patronato",
  },
  {
    absoluteNum: 538,
    teamNum: 529,
    playerName: null,
    isSelected: false,
    team: "Patronato",
  },
  {
    absoluteNum: 539,
    teamNum: 530,
    playerName: null,
    isSelected: false,
    team: "Patronato",
  },
  {
    absoluteNum: 540,
    teamNum: 531,
    playerName: null,
    isSelected: false,
    team: "Patronato",
  },
  {
    absoluteNum: 541,
    teamNum: 532,
    playerName: null,
    isSelected: false,
    team: "Patronato",
  },
  {
    absoluteNum: 542,
    teamNum: 533,
    playerName: null,
    isSelected: false,
    team: "Patronato",
  },
  {
    absoluteNum: 543,
    teamNum: 534,
    playerName: null,
    isSelected: false,
    team: "Patronato",
  },
  {
    absoluteNum: 544,
    teamNum: 535,
    playerName: null,
    isSelected: false,
    team: "Patronato",
  },
  {
    absoluteNum: 545,
    teamNum: 536,
    playerName: null,
    isSelected: false,
    team: "Patronato",
  },
  {
    absoluteNum: 546,
    teamNum: 537,
    playerName: null,
    isSelected: false,
    team: "Patronato",
  },
  {
    absoluteNum: 547,
    teamNum: 538,
    playerName: null,
    isSelected: false,
    team: "Patronato",
  },
  {
    absoluteNum: 548,
    teamNum: 539,
    playerName: null,
    isSelected: false,
    team: "Patronato",
  },
  {
    absoluteNum: 549,
    teamNum: 540,
    playerName: null,
    isSelected: false,
    team: "Patronato",
  },
  {
    absoluteNum: 550,
    teamNum: 541,
    playerName: null,
    isSelected: false,
    team: "Patronato",
  },
  {
    absoluteNum: 551,
    teamNum: 542,
    playerName: null,
    isSelected: false,
    team: "Patronato",
  },
  {
    absoluteNum: 552,
    teamNum: 543,
    playerName: null,
    isSelected: false,
    team: "Patronato",
  },
  {
    absoluteNum: 553,
    teamNum: 544,
    playerName: null,
    isSelected: false,
    team: "Patronato",
  },
  {
    absoluteNum: 554,
    teamNum: 10,
    playerName: null,
    isSelected: false,
    team: "CL",
  },
  {
    absoluteNum: 555,
    teamNum: 11,
    playerName: null,
    isSelected: false,
    team: "CL",
  },
  {
    absoluteNum: 556,
    teamNum: 12,
    playerName: null,
    isSelected: false,
    team: "CL",
  },
  {
    absoluteNum: 557,
    teamNum: 13,
    playerName: null,
    isSelected: false,
    team: "CL",
  },
];
