import "./globals.css";
import type { Metadata } from "next";
import { Lilita_One } from "next/font/google";
import { NextAuthProvider } from "./context/NextAuthProvider";

const lilita_one_font = Lilita_One({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Control de Figus",
  description: "Generated by Andrés Drimer",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lilita_one_font.className}>
        <NextAuthProvider>
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
