import './globals.css'
import type { Metadata } from 'next'
import { Lilita_One } from 'next/font/google'

const lilita_one_font = Lilita_One({ subsets: ['latin'], weight: ["400"] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={lilita_one_font.className}>{children}</body>
    </html>
  )
}
